[package]
name = "interpol"
version = "0.1.0"
edition = "2021"

[dependencies]
cpal = { version = "0.15.3", features = ["jack"] }
anyhow = "1.0.95"
clap = { version = "4.5.29", features = ["derive"] }
realfft = "3.4.0"
ringbuf = "0.4.7"
rustfft = "6.2.0"
